title: GitHub pages tutorial
author: Matt Myint
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a filler, I'll leave the default text here so that I know how to
  fix up my own site later.
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
